name: 'OpenCommit GitHub Action'
description: 'Checks commit messages and replaces "oc" with a smart AI generated message'
author: 'https://github.com/di-sukharev'

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node12'
  main: 'dist/github-action.js'
