name: 'OpenCommit GitHub Action'
description: 'Checks commit messages and replaces "oc" with a smart and impressive AI generated message 🤯🔫'
author: 'https://github.com/di-sukharev'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/github-action.cjs'
